"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import alert from './alert';
var Modal_1 = require("./Modal");
// import operation from './operation';
// import prompt from './prompt';
// Modal.alert = alert;
// Modal.prompt = prompt;
// Modal.operation = operation;
exports.default = Modal_1.default;
